---
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: admin
  namespace: teleport
spec:
  allow:
    logins:
      - admin
    kubernetes_groups: 
      - edit
    node_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: '*'
        namespace: '*'
        name: '*'
        verbs:
          - '*'
