chartMode: standalone
clusterName: teleport-cluster.teleport.svc.cluster.local

operator:
  enabled: true

proxyListenerMode: "multiplex"

authentication:
  type: local # Possible values are 'local' and 'github' for OSS, plus 'oidc' and 'saml' for Enterprise.
  connectorName: local
  localAuth: true
  lockingMode: best_effort
  secondFactor: "on"

auth:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    auth_service:
      web_idle_timeout: 1h
      authentication:
        locking_mode: best_effort

proxy:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    proxy_service:
      https_keypairs_reload_interval: 12h
      public_addr: teleport.example.com:443
      tunnel_public_addr: teleport.example.com:3024

  annotations:
    ingress:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

podSecurityPolicy:
  enabled: false

highAvailability:
  replicaCount: 2
  requireAntiAffinity: false
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  certManager:
    enabled: true
    addCommonName: false
    addPublicAddrs: false
    issuerName: "selfsigned-issuer"
    issuerKind: ClusterIssuer
    issuerGroup: cert-manager.io

service:
  enabled: true
  type: ClusterIP
  port: 443
  targetPort: 3080

publicAddr:
  - teleport.example.com:443

ingress:
  enabled: true
  spec:
    ingressClassName: nginx
    tls:
      - hosts:
          - teleport.example.com
        secretName: teleport-tls

persistence:
  enabled: true

tls:
  enabled: true
  existingSecret: teleport-tls
  existingCASecretName: teleport-tls
