chartMode: standalone
clusterName: teleport.example.com

proxyListenerMode: "multiplex"

auth:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    # auth_service:
    #   enabled: false
    #   web_idle_timeout: 1h
    #   authentication:
    #     locking_mode: best_effort

proxy:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    proxy_service:
      https_keypairs_reload_interval: 12h
      public_addr: teleport.example.com:443
      tunnel_public_addr: teleport.example.com:3024

  annotations:
    ingress:
      cert-manager.io/cluster-issuer: selfsigned-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

podSecurityPolicy:
  enabled: false

highAvailability:
  replicaCount: 2

service:
  enabled: true
  type: ClusterIP
  port: 443
  targetPort: 3080

publicAddr:
  - teleport.example.com:443

ingress:
  enabled: true
  spec:
    ingressClassName: nginx
    tls:
      - hosts:
          - teleport.example.com
        secretName: teleport-example-com-tls

persistence:
  enabled: false

# tls:
#   enabled: true
#   existingSecret: teleport-example-com-tls
#   existingCASecretName: teleport-example-com-tls
