chartMode: standalone
clusterName: teleport.example.com

proxyListenerMode: "multiplex"

auth:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    auth_service:
      enabled: true
      web_idle_timeout: 1h
      authentication:
        locking_mode: best_effort

proxy:
  teleportConfig:
    teleport:
      log:
        output: stderr
        severity: DEBUG

    proxy_service:
      https_keypairs_reload_interval: 12h
      public_addr: custom.example.com:443
      tunnel_public_addr: custom.example.com:3024

podSecurityPolicy:
  enabled: false

highAvailability:
  replicaCount: 2

service:
  enabled: true
  type: ClusterIP
  port: 3080
  targetPort: 3080 

ingress:
  enabled: true
  spec:
    ingressClassName: nginx
  name: teleport-ui-ingress
  hosts:
    - host: teleport.example.com
      paths:
        - /
  tls:
    - secretName: teleport-example-com-tls
      hosts:
        - teleport.example.com 
